### ISSUE TITLE
VUnit lib string_ptr_pkg-body-2002p compilation error

### ISSUE THREAD

**Issue by edsonms** [TerosTechnology/terosHDL#67]
Hi,

Working with TerosHDL v1.1.7 on macOS Catalina 10.15.4 and whenever I try to use VUnit test it returns a library compilation error:

> Compiling into vunit_lib: ../../../../../../Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd               
> 
> failed
> === Command used: ===
> /usr/local/bin/ghdl -a --workdir=/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/vunit_lib --work=vunit_lib --std=08 -P/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/vunit_lib -P/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/src_lib -P/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/tb_lib /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd

Any ideas guys?

**Comment by qarlosalberto** [comment]
Could you re-run with --verbose argument and put the complete output?

**Comment by edsonms** [comment]
> Could you re-run with --verbose argument and put the complete output?

Do you mean to add --verbose here?
![image](https://user-images.githubusercontent.com/27818470/82161286-c742ed80-9871-11ea-893c-24814141b44a.png)
It returns the same error as before:

> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/builtins.py:136: Warning: 'array_t' is deprecated and it will removed in future releases;use 'integer_array_t' instead
>   warn(arr_deprecation_note, Warning)
> 
> =============================================
> ghdl
> =============================================
> Compiling into vunit_lib: ../../../../../../Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd         
> 
> failed
> === Command used: ===
> /usr/local/bin/ghdl -a --workdir=/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/vunit_lib --work=vunit_lib --std=08 -P/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/vunit_lib -P/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/src_lib -P/Users/edson/Documents/Documentos_Eletronica/Pos_IFSC/Projeto_TC/Radar_idea/FPGA_Flow_Detector/vunit_out/ghdl/libraries/tb_lib /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd
> 
> === Command output: ===
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'm' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'i' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character ':' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'i' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character '/' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character '=' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character '-' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character '1' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 's' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'u' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'p' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'p' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:132:32: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'm' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'x' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packa
> 
> ges/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character ':' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'i' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'm' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'u' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 's' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'b' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'u' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:134:33: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'i' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'm' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'p' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'm' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'f' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'x' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'e' of type character is not visible
> /Users/edson/
> 
> Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character ' ' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'm' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:177:46: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'd' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'c' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:186:27: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'l' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'c' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'a' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:242:31: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:273:31: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:273:31: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:273:31: character 's' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:273:31: character 'i' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:273:31: character 'z' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:273:31: character 'e' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 'o' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character '_' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 's' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 't' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 'r' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 'i' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 'n' of type character is not visible
> /Users/edson/Library/Python/2.7/lib/python/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd:287:31: character 'g' of type character is not visible
> /usr/local/bin/ghdl: compilation error
> 
> Compile failed
